# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-28 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='id',
        ),
        migrations.AddField(
            model_name='question',
            name='ques_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
