# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 07:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20170528_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='description',
            new_name='ans_description',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='ques_description',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='title',
            new_name='ques_title',
        ),
    ]
