# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 10:26
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20170529_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ques_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
