# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 10:28
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20170529_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='ans_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
