# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_auto_20170530_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ques_title',
            field=models.CharField(max_length=5000, verbose_name='Question Title'),
        ),
    ]
